In [17]:
import pandas as pd
df=pd.read_csv("fake_job_postings.csv")
df['description'][3]

"THE COMPANY: ESRI – Environmental Systems Research InstituteOur passion for improving quality of life through geography is at the heart of everything we do.\xa0 Esri’s geographic information system (GIS) technology inspires and enables governments, universities and businesses worldwide to save money, lives and our environment through a deeper understanding of the changing world around them.Carefully managed growth and zero debt give Esri stability that is uncommon in today's volatile business world.\xa0 Privately held, we offer exceptional benefits, competitive salaries, 401(k) and profit-sharing programs, opportunities for personal and professional growth, and much more.THE OPPORTUNITY: Account ExecutiveAs a member of the Sales Division, you will work collaboratively with an account team in order to sell and promote adoption of Esri’s ArcGIS platform within an organization. As part of an account team, you will be responsible for facilitating the development and execution of a set of strategies for a defined portfolio of accounts. When executing these strategies you will utilize your experience in enterprise sales to help customers leverage geospatial information and technology to achieve their business goals.\xa0Specifically…Prospect and develop opportunities to partner with key stakeholders to envision, develop, and implement a location strategy for their organizationClearly articulate the strength and value proposition of the ArcGIS platformDevelop and maintain a healthy pipeline of opportunities for business growthDemonstrate a thoughtful understanding of insightful industry knowledge and how GIS applies to initiatives, trends, and triggersUnderstand the key business drivers within an organization and identify key business stakeholdersUnderstand your customers’ budgeting and acquisition processesSuccessfully execute the account management process including account prioritization, account resourcing, and account planningSuccessfully execute the sales process for all opportunitiesLeverage and lead an account team consisting of sales and other cross-divisional resources to define and execute an account strategyEffectively utilize and leverage the CRM to manage opportunities and drive the buying processPursue professional and personal development to ensure competitive knowledge of the real estate industryLeverage social media to successfully prospect and build a professional networkParticipate in trade shows, workshops, and seminars (as required)Support visual story telling through effective whiteboard sessionsBe resourceful and takes initiative to resolve issues"

In [18]:
fraud=df[df['fraudulent']==1]
fraud

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
98,99,IC&E Technician,"US, , Stocton, CA",Oil & Energy,95000-115000,...,"IC&amp;E Technician | Bakersfield, CA Mt. Poso...","QualificationsKnowledge, Skills &amp; Abilitie...",BENEFITSWhat is offered:Competitive compensati...,0,1,1,Full-time,Mid-Senior level,High School or equivalent,Oil & Energy,Other,1
144,145,Forward Cap.,NaN,NaN,NaN,NaN,The group has raised a fund for the purchase o...,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,1
173,174,Technician Instrument & Controls,US,Power Plant & Energy,NaN,Edison International and Refined Resources hav...,Technician Instrument &amp; ControlsLocation D...,JOB QUALIFICATIONS-Ability to understand proce...,"we are a team of almost 8,000 employees who he...",0,1,1,Full-time,Mid-Senior level,Certification,Electrical/Electronic Manufacturing,Other,1
180,181,Sales Executive,"PK, SD, Karachi",Sales,NaN,NaN,Sales Executive,Sales Executive,Sales Executive,0,0,0,NaN,NaN,NaN,NaN,Sales,1
215,216,IC&E Technician Mt Poso,"US, CA, Bakersfield, CA / Mt. Poso",Oil & Energy,95000-115000,...,"IC&amp;E Technician | Bakersfield, CA Mt. Poso...","QualificationsKnowledge, Skills &amp; Abiliti...",BENEFITSWhat is offered:Competitive compensati...,0,1,1,Full-time,Mid-Senior level,High School or equivalent,Oil & Energy,Other,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17827,17828,Student Positions Part-Time and Full-Time.,"US, CA, Los Angeles",NaN,NaN,NaN,Student Positions Part-Time and Full-Time.You ...,NaN,NaN,0,0,0,Part-time,NaN,NaN,NaN,NaN,1
17828,17829,Sales Associate,"AU, NSW, Sydney",Sales and Marketing,NaN,NaN,LEARN TO EARN AN EXECUTIVE LEVEL INCOMEFULL TR...,What You Can Do. • Have the potential to earn ...,Who We Are We are a Global Leadership Developm...,0,0,1,NaN,NaN,NaN,NaN,NaN,1
17829,17830,Android Developer,"PL, MZ, Warsaw",NaN,NaN,NaN,inFullMobile Sp. z o.o. is a mobile software d...,• A proven track record in Android / JAVA proj...,attractive salary (adequate to the candidate s...,0,0,0,NaN,NaN,NaN,NaN,NaN,1
17830,17831,Payroll Clerk,"US, NY, New York",NaN,NaN,NaN,JOB DESCRIPTIONWe are seeking a full time payr...,JOB REQUIREMENTS• High school diploma or eq...,We offer a competitive salary and benefits pac...,0,0,0,Full-time,NaN,NaN,Apparel & Fashion,Accounting/Auditing,1
17831,17832,Furniture mover,"US, IL, Chicago",NaN,NaN,Anthony Warren is a Marketing and Advertising ...,earn $500 to $1000 a week as a mover. Must ha...,Good liftflexibile schedulegeat attitude,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,1

In [14]:
Title=fraud['title']
Description=fraud['description']

In [27]:
fraud_df=pd.DataFrame({
    "Title":Title,
    "Description":Description,
    "IS_Scam":1,
})

In [28]:
fraud_df

,Title,Description,IS_Scam
98,IC&E Technician,"IC&amp;E Technician | Bakersfield, CA Mt. Poso...",1
144,Forward Cap.,The group has raised a fund for the purchase o...,1
173,Technician Instrument & Controls,Technician Instrument &amp; ControlsLocation D...,1
180,Sales Executive,Sales Executive,1
215,IC&E Technician Mt Poso,"IC&amp;E Technician | Bakersfield, CA Mt. Poso...",1
...,...,...,...
17827,Student Positions Part-Time and Full-Time.,Student Positions Part-Time and Full-Time.You ...,1
17828,Sales Associate,LEARN TO EARN AN EXECUTIVE LEVEL INCOMEFULL TR...,1
17829,Android Developer,inFullMobile Sp. z o.o. is a mobile software d...,1
17830,Payroll Clerk,JOB DESCRIPTIONWe are seeking a full time payr...,1
17831,Furniture mover,earn $500 to $1000 a week as a mover. Must ha...,1

## Save final fraud data

In [29]:
fraud_df.to_csv("Final_fraud_Internship.csv",index=True)

## Now satrt merging both real and fake dataset

In [30]:
real_internship=pd.read_csv('internshala_real_internship.csv')

fake_internship=pd.read_csv('Final_fraud_Internship.csv', index_col=0)

fake_internship.columns

Index(['Title', 'Description', 'IS_Scam'], dtype='object')

In [31]:
real_internship['Description'][1]

'The coolest weekend internship is here!\n\nGet a chance to work with one of the most iconic brands, interact with international customers, and earn a prestigious certificate and a stipend of    13,000/- that turns heads. And yes, free food, snacks, and beverages too!\n\nAll of this in a 8-day weekend internship as per the following schedule:\n\nOnboarding & training (can be in any shift - day shift or the evening shift): \n\n1. 28th July /13th August (Mon - Fri, onboarding)\n2. 17th August (Sun, training)\n3. 24th  August (Sun, training)\n4. 30th & 31st August (Sat & Sun, training)\n\nProduction i.e. actual working (night shift):\n\n1. 7th September (Sun)\n2. 14th September(Sun)\n3. 21st September (Sun)\n\nWhat will you do in the internship: \n\n1. Provide excellent customer service over the phone.\n2. Adhere to program-defined quality standards.\n3. Stay informed about the latest information and updates.\n4. Perform tasks related to voice profiles.\n\nSince the internship requires interacting with international clients, you must possess excellent English-speaking skills. \n\nYou must be comfortable with either the day shift or the evening shift on the training and onboarding dates and night shifts (only) on the production dates. Also, you would need to clear the training to proceed further with the production phase.\n\nThe internship location would be in Hyderabad. Please apply to this internship ONLY if you are available on the above dates and shifts and can arrange for your own transport to the office. Other than the stipend, no cab allowance would be provided. Free food/snacks and beverages would be available during cafeteria operating hours.'

In [32]:
fake_internship['Description'][98]

'IC&amp;E Technician | Bakersfield, CA Mt. PosoPrincipal Duties and Responsibilities:\xa0Calibrates, tests, maintains, troubleshoots, and installs all power plant instrumentation, control systems and electrical equipment.Performs maintenance on motor control centers, motor operated valves, generators, excitation equipment and motors.Performs preventive, predictive and corrective maintenance on equipment, coordinating work with various team members.Designs and installs new equipment and/or system modifications.Troubleshoots and performs maintenance on DC backup power equipment, process controls, programmable logic controls (PLC), and emission monitoring equipment.Uses maintenance reporting system to record time and material use, problem identified and corrected, and further action required; provides complete history of maintenance on equipment.Schedule, coordinate, work with and monitor contractors on specific tasks, as required.Follows safe working practices at all times.Identifies safety hazards and recommends solutions.Follows environmental compliance work practices.Identifies environmental non-compliance problems and assist in implementing solutions.Assists other team members and works with all departments to support generating station in achieving their performance goals.Trains other team members in the areas of instrumentation, control, and electrical systems.Performs housekeeping assignments, as directed.Conduct equipment and system tagging according to company and plant rules and regulations.Perform equipment safety inspections, as required, and record results as appropriate.\xa0Participate in small construction projects.\xa0 Read and interpret drawings, sketches, prints, and specifications, as required.Orders parts as needed to affect maintenance and repair.Performs Operations tasks on an as-needed basis and other tasks as assigned.Available within a reasonable response time for emergency call-ins and overtime, plus provide acceptable off-hour contact by phone and company pager.\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Excellent Verbal and Written Communications Skills:Ability to coordinate work activities with other team members on technical subjects across job families.Ability to work weekends, holidays, and rotating shifts, as required.'

In [33]:
# I need only title and desciption on internship 

real_internship1=pd.DataFrame({
    'Title':real_internship['Title'],
    'Description':real_internship['Description'],
    'IS_Scam':real_internship['IS_Scam']
})
real_internship1.head()

,Title,Description,IS_Scam
0,NaN,NaN,0
1,International Customer Service: The Coolest We...,The coolest weekend internship is here!\n\nGet...,0
2,Digital Marketing,Are you a savvy digital marketer looking to ga...,0
3,Digital Marketing,Selected intern's day-to-day responsibilities ...,0
4,Fashion Design Business Development,Are you passionate about fashion and looking t...,0

In [34]:
# lets concat both data file(real and fake)

joined_df=pd.concat([fake_internship,real_internship1], ignore_index=True)
joined_df

,Title,Description,IS_Scam
0,IC&E Technician,"IC&amp;E Technician | Bakersfield, CA Mt. Poso...",1
1,Forward Cap.,The group has raised a fund for the purchase o...,1
2,Technician Instrument & Controls,Technician Instrument &amp; ControlsLocation D...,1
3,Sales Executive,Sales Executive,1
4,IC&E Technician Mt Poso,"IC&amp;E Technician | Bakersfield, CA Mt. Poso...",1
...,...,...,...
2509,Media & Public Relations (PR),We're looking for a PR-savvy Journalism intern...,0
2510,Marketing,Selected intern's day-to-day responsibilities ...,0
2511,Operations,Are you a proactive and detail-oriented indivi...,0
2512,Online Sanskrit Faculty For School Kids.,Selected intern's day-to-day responsibilities ...,0
2513,Online Hindi Faculty For School Kids.,Selected intern's day-to-day responsibilities ...,0

In [39]:
# Shufffling data
final_df = joined_df.sample(frac=1).reset_index(drop=True)
final_df

,Title,Description,IS_Scam
0,Customer Service Representative,SUMMARYResponsible for acting as a liaison bet...,1
1,Social Media Marketing,Selected intern's day-to-day responsibilities ...,0
2,Remote Data Entry Rep Needed,We're looking for self-motivated individuals w...,1
3,Data Entry Office Support,We are seeking individuals to be connected wit...,1
4,Hiring for Business Intelligence and Analytic...,"Position :Manager, Software DevelopmentJob Typ...",1
...,...,...,...
2509,Human Resources (HR),Selected intern's day-to-day responsibilities ...,0
2510,Call Center Representative I,The Call Center Representative I will provide ...,1
2511,NaN,NaN,0
2512,Operating Room Director,Apply using below link#URL_0243c9ffa14e848cbe0...,1
2513,Project QA Engineer,Corporate overviewAker Solutions is a global p...,1

In [40]:
# save final combined dataset
final_df.to_csv("Final_internship_dataset.csv",index=False)